### PR TITLE
WIP: Update installation guide

### PR DESCRIPTION
**Pull request by willirath**
I start this PR to address #225 and #104 and to discuss and maybe settle on a way of documenting different ways of installing parcels. Currently, this PR only contains a hint on how to re-organize the "Installing Parcels" section of the documentation.

### CODE REVIEW

**Comment by erikvansebille** [comment]
Thanks @willirath for starting this PR! I myself have also been working on a branch yesterday and today, based on your recommendations in #225. See https://github.com/OceanParcels/parcels/tree/install_via_conda

There were some other issues with Travis that needed to be fixed too, but we now have a working(?) version of the install script in `.travis.yml`

I'll merge with your suggestions for the `index.rst` and then hopefully this fixes #225 and #104?

**Comment by willirath** [comment]
> There were some other issues with Travis that needed to be fixed too, but we now have a working(?) version of the install script in .travis.yml

The tests that failed here seem to be at least partly related to a matplotlib bug which I've circumvented by pinning `matplotlib=2.0.2`.

**Comment by willirath** [comment]
> I'll merge with your suggestions for the index.rst and then hopefully this fixes #225 and #104?

This would (from a more outside perspecitve) solve #104 and #225. 

What's your opinion on the space all this should take in the documentation?  I'd go for a pretty detailed (but robust) description of the following scenarios:

1. How to install master with conda?

2. How to install with pure pip? (which involves making sure that there's a working ffmpeg, compiler, netCDF-lib, etc. on ones own)

3. How to pick a different Git reference? (like the HEAD of some other branch, fork, ...)

From 02e833a9c16a50f91ebddfba87109e61056b2b7f, I gather that you'd prefer a concise documentation, though.  Not sure if an elaborated  installation guide contradicts this.

Then, there still is the possibility of providing a conda-forge package. This adds some additional maintenance tasks though.

Let's just see whatever is working for you.  I'd be happy to get involved in any of the possible solutions.

**Comment by willirath** [comment]
A few suggestions regarding <https://github.com/OceanParcels/parcels/tree/install_via_conda>:

I'd remove the explicit parcels installation from the `environment.yml`. (See below for why this makes any sense at all.)

<https://github.com/OceanParcels/parcels/blob/effc1c2a61c9e4e83471df11d05b26ab2e0c10a9/.travis.yml#L27-L30>

is problematic because it first installs a Python version determined by a Travis environment variable and then ignores it by setting up a completely new env.  I'd go for

```yaml
    - conda env create --file environment.yml
    - source activate py2_parcels
    - conda install --yes python=$TRAVIS_PYTHON_VERSION
    - pip install -e .
```

which first sets up the environment as defined in `environment.yml`, activates it and only then enforces whatever Python version Travis wants. The last step then installs Parcels for whatever Git ref the job is running for. (If we'd leave an explicit `pip install parcels` in the env file, we'd always get an env that's at least in part determined what the master branch is pointing at.)

As all the hdf- and netCDF dependencies are now satisfied via conda-forge, all of the following should be safe to be omitted:

<https://github.com/OceanParcels/parcels/blob/effc1c2a61c9e4e83471df11d05b26ab2e0c10a9/.travis.yml#L11-L16>

The following is obsolete as pip now takes care of wiring everything for parcels:

<https://github.com/OceanParcels/parcels/blob/effc1c2a61c9e4e83471df11d05b26ab2e0c10a9/.travis.yml#L38>

With these changes, an installation could be done by just running:

```bash
Parcels_ref=master # or whatever branch or commit you want to install
conda env create --file environment.yml
source activate py2_parcels
pip install git+https://github.com/OceanParcels/parcels@${Parcels_ref}
```

To install from a fork or from some other ref, a user just needs to change the last line of this snippet.

**Comment by willirath** [comment]
> I'd remove the explicit parcels installation from the environment.yml. (See below for why this makes any sense at all.)

That is, remove: 
<https://github.com/OceanParcels/parcels/blob/effc1c2a61c9e4e83471df11d05b26ab2e0c10a9/environment.yml#L27>

**Comment by willirath** [comment]
@erikvansebille Perhaps I should close this PR and send you one for the `install_via_conda` branch?

**Comment by erikvansebille** [comment]
Thanks @willirath for all these suggestions on the branch. I've just created a PR from that (#228)

Would be good if you could merge your proposed changes to the `index.rst` (and any other input you have; you're clearly much more an expert on this than I am!) to that PR. Then we can close this PR?

**Comment by willirath** [comment]
As #228 is dealing with this now, I'll close here.

**Pull request closed without merging**
