### PR TITLE
Better print for jit

### PR DESCRIPTION
**Pull request by delandmeterp**
Some improvement of the print functionalities in the python kernels for JIT.

For example, such kernel is now possible:

def UpdateP(particle, fieldset, time, dt):
    particle.p = fieldset.P[time, particle.lon, particle.lat, particle.depth]
    print(particle.p)
    b = particle.p
    xi = particle.xi
    print("I will print my Particle data")
    print("particle.p  %f %d" % (b, xi))

### CODE REVIEW

**Comment by erikvansebille** [comment]
Oh, and should we also unit-test this? Or is that overdoing it?

**Comment by erikvansebille** [comment]
Actually, I just realised I once wrote a unit-test for printing already, but that it was xfailing. Now with this PR it works, so I've just pushed a commit so that now the printing is indeed tested

**Comment by delandmeterp** [comment]
Perfect, there is still one thing I have to do.
If we advertise that we can do print in the kernels (of course it slows down the code, so it's for debugging), it has to be cleaner.

For the moment, we can do:
p = particle.p
print("check %g" % p)

but I haven't implemented that we do 
print("check %g" % particle.p)

So, I'll clean it, such that it works

**Comment by erikvansebille** [comment]
Is that really true, @delandmeterp? I just simplified the print unit test, and it seems to work perfectly fine for
```
def kernel(particle, fieldset, time, dt):
    particle.p = fieldset.U[time, particle.lon, particle.lat, particle.depth]
    print("%d %f" % (particle.id, particle.p))
```

**Comment by delandmeterp** [comment]
Yes indeed. I've just also checked and it works. I wasn't sure the the py_ast commands were working recursively in what I've done. But everything is right :-)

**Pull request merged**
