### PR TITLE
masking update for AdvectionRK4 method

### PR DESCRIPTION
**Pull request by nathanieltarshish**
Before interpolating to find the velocity at a given (lat, lon), we
check to see if (lat, lon) are in the grid domain. If they are in the
domain , we proceed to the velocity interpolation step. If they are
outside the domain, the particle has exited and the coordinates get
masked to np.nan. Note that np.nan masking is compatible with the show
movie feature of the execute method and the plotParticles 2d mode
script.

### CODE REVIEW

**Comment by nathanieltarshish** [comment]
The scipy version works, but the jit version fails. I am looking into it.

**Comment by mlange05** [comment]
Ok, so unfortunately this approach looks somewhat incompatible with our current JIT engine, since we currently don't support generic numpy functionality in the kernels. The main point goes deeper though, since the plan for this type of feature is to perform the containment check as part of the underlying time loop engine itself, and then invoke a separate, possibly user-defined, "failure kernel" that specifies the recovery behaviour. This planned approach is essentially part of the planned parallelisation, since one of the "recovery mechanisms" here is to send the particle to a different partition of the grid.

That being said though, I don't mind intermediate short-term workarounds, but they do need to consider the JIT engine, I'm afraid.

**Comment by nathanieltarshish** [comment]
Thanks for the explanation. I did not understand that you wanted a generic time loop engine with a distinct recovery kernel. I could only think of a few different behaviors that a user would desire for particles reaching the boundary: mask the particle, remove the particle data, or enforce circumpolar boundary conditions. Given the limited number of cases, I thought there would be a different time loop engine corresponding to each case (and by passing a flag to ParticleSet.execute, the user would specify the desired engine/behavior at the boundary). However, I understand that ideally the code would be as modular as possible to facilitate parallelization.  

As you mentioned, it would be great to have an intermediate workaround. I assume that the generic numpy functionality that was problematic was the usage of the np.nan datatype and the np.isnan function. Do you know of any JIT-compatible alternatives? Are there other JIT incompatibilities to the proposed code that I have overlooked?

**Comment by erikvansebille** [comment]
We have just landed PR #85, which tries to solve the issue in the field interpolator, rather than the RK4 function. I had a chat with @mlange05 and since that solution was so much smaller and less impactful (it doesn't interfere with the 3D velocities PR), we decided to first land the field interpolator hack. 

We are aware that the 'true' solution to this out-of-bounds problem requires proper error handling and passing. This is also tightly linked in to the parallelisation (Issue #17), since another case where particles reach domain boundaries is  when they need to be moved from one tile to another, in parallel execution.

As for JIT functionality of np.nan, that is not supported yet. Will need some work to implement, unfortunately. Hopefully we can land a proper solution in a week or so!

**Comment by nathanieltarshish** [comment]
Thanks for the update! I could not tell if the "proper solution" that you mention at the end of your comment refers to building the ideal solution (error handling and passing ) or a short-term solution (like building in np.nan functionality). In case it referred to a short-term solution, I just wanted to mention that on the scipy side, the code works equally well with the math package's nan implementation (math.isnan() function and float('nan') datatype ). I am new to the JIT world, but thought that the math implementation may be easier to make JIT-compatible than the numpy implementation. Either way, I appreciate your help and explanations.

**Comment by nathanieltarshish** [comment]
Thanks for the update! I could not tell if the "proper solution" that you
mention at the end of your comment refers to building the ideal solution
(error handling and passing ) or a short-term solution (like building
in np.nan functionality). In case it referred to a short-term solution, I
just wanted to mention that on the scipy side, the code works equally well
with the math package's nan implementation (math.isnan() function and
float('nan') datatype ). I am new to the JIT world, but thought that the
math implementation may be easier to make JIT-compatible than the numpy
implementation. Either way, I appreciate your help and explanations.

**Pull request merged**
