### PR TITLE
Updating documentation_MPI notebook to use new chunksize API

### PR DESCRIPTION
**Pull request by erikvansebille**
Note that, because the documentation and tutorials follow the releases of Parcels, this PR should only be merged after #932 is merged into master _and_  this master is released. That is also why this change is a different PR than #932

### CODE REVIEW

**Review by reint-fischer — APPROVED** [review]
These are the types of updates to documentation/tutorials that are very nice to do immediately and release later

**Comment by CKehl** [comment]
Is this PR now concluded ?

**Review by CKehl — APPROVED** [review]

**Comment by erikvansebille** [comment]
We're waiting until the release of the next version of Parcels (v2.2.2) so that the notebook on the website aligns with the conda-version of Parcels. That's why it's not merged yet

**Comment by reint-fischer** [comment]
I have added the documentation of the `populate_indices` function introduced in #954 . @erikvansebille, can you check if this is correct?

**Comment by angus-g** [comment]
The example in the documentation does indeed match the intended use of the function: you only need to call it to perform the initial index search.

**Comment by erikvansebille** [comment]
I've done some minor rewording of the documentation, but it looks good! This is ready for merging after we release version 2.2.2

**Pull request merged**
