### PR TITLE
Fix bool deprecation warning

### PR DESCRIPTION
**Pull request by erikvansebille**
Fixes a deprecation warning in numpy (see #1119) by changing `Grid.z4d` to an int (instead of bool), as suggested by @CKehl

### CODE REVIEW

**Comment by CKehl** [comment]
question is: did it solve the issue - is the warning not emitted anymore ?

**Comment by erikvansebille** [comment]
Was just checking; unfortunately the warning still seems to be triggered, see https://github.com/OceanParcels/parcels/runs/4804848493?check_suite_focus=true#step:3:3636 and https://github.com/OceanParcels/parcels/runs/4804848629?check_suite_focus=true#step:3:6245

**Comment by CKehl** [comment]
well, okay, so looking at the code again, the required structure is:
```
            _fields_ = [('xdim', c_int), ('ydim', c_int), ('zdim', c_int),
                        ('tdim', c_int), ('z4d', c_int),
                        ('mesh_spherical', c_int), ('zonal_periodic', c_int),
                        ('chunk_info', POINTER(c_int)),
                        ('load_chunk', POINTER(c_int)),
                        ('tfull_min', c_double), ('tfull_max', c_double), ('periods', POINTER(c_int)),
                        ('lonlat_minmax', POINTER(c_float)),
                        ('lon', POINTER(c_float)), ('lat', POINTER(c_float)),
                        ('depth', POINTER(c_float)), ('time', POINTER(c_double))
                        ]
```
the actual parameters are:
```
            self.cstruct = CStructuredGrid(self.xdim, self.ydim, self.zdim,
                                           self.tdim, self.z4d,
                                           self.mesh == 'spherical', self.zonal_periodic,
                                           (c_int * len(self.chunk_info))(*self.chunk_info),
                                           self.load_chunk.ctypes.data_as(POINTER(c_int)),
                                           self.time_full[0], self.time_full[-1], pointer(self.periods),
                                           self.lonlat_minmax.ctypes.data_as(POINTER(c_float)),
                                           self.lon.ctypes.data_as(POINTER(c_float)),
                                           self.lat.ctypes.data_as(POINTER(c_float)),
                                           self.depth.ctypes.data_as(POINTER(c_float)),
                                           self.time.ctypes.data_as(POINTER(c_double)))
```

in this frame, there are 2 further variables that are defined as `int` but set as `bool`:
```
self.mesh == 'spherical', self.zonal_periodic
```
that can be casted explicitly as
```
int(self.mesh == 'spherical'), int(self.zonal_periodic)
```

Otherwise, if you have other ways to explicitly cast the `bool`'s to `int`'s, then feel free to do it your way. Buth both those variables still need to be cast to int.

**Comment by erikvansebille** [comment]
OK, also casting `int(self.mesh == 'spherical'), int(self.zonal_periodic)` did the trick; the warning has now disappeared from the CI!

**Review by CKehl — APPROVED** [review]

**Pull request merged**
