### PR TITLE
Fix Binder filepath typo

### PR DESCRIPTION
**Pull request by VeckoTheGecko**
Fixes https://github.com/OceanParcels/parcels/pull/1368#issuecomment-1581932278

Path should be `docs/examples` not `parcels/docs/examples`

### CODE REVIEW

**Comment by erikvansebille** [comment]
Do you know if there's a way to have the binder default open with the filelist? It now opens with the landing page where users can select a clean notebook; but that is probably not what most users want. If they're new to Jupyter, they may not realise they have top click the file tab to see all the tutorials and examples

**Comment by VeckoTheGecko** [comment]
I don't think theres an option to have the tree open automatically. Maybe if we have the notebook open on `parcels_tutorial.ipynb` then they can know that its working, and see the folder icon in the top-left to explore further?

**Comment by erikvansebille** [comment]
> I don't think theres an option to have the tree open automatically. Maybe if we have the notebook open on `parcels_tutorial.ipynb` then they can know that its working, and see the folder icon in the top-left to explore further?

Yes, that's the way it used to be. I'll implement that option on oceanparcels.org; can you change it here on the parcels repo?

**Comment by VeckoTheGecko** [comment]
Done

**Review by erikvansebille — APPROVED** [review]

**Pull request merged**
