### PR TITLE
Calendar parsing

### PR DESCRIPTION
**Pull request by jbusecke**
I attempted to enable parcels to carry the cftime calendars through to the output (#602).
I added two utility functions `_get_cftime_calendars` and `_get_cftime_datetimes` which return lists of all available calendars and corresponding datetime instances. 
The other changes mostly just implement these two functions and I added some tests. 

I am not very familiar with the code structure, and am happy to rearrange things.

### CODE REVIEW

**Comment by willirath** [comment]
@jbusecke I've fixed a small typo in an import statement in the tests see if Travis makes it then.  Didn't have a closer look yet, though.

**Comment by jbusecke** [comment]
There was a bug in `test_set_calendar`, but that import statement is curious. My version works for me locally. Did I start from the wrong branch?

Ughh I also just noticed that I messed up the merge. Let me correct that...

**Comment by willirath** [comment]
Looks like it's gone wrong again.  For ca42fbb99114d9de2eeb83103243f9d9f7b8d872 travis jobs seem to do fine up to flake errors: <https://travis-ci.org/OceanParcels/parcels/jobs/544224870#L1619>

**Comment by jbusecke** [comment]
Sorry for the style errors. I usually use black but I wanted to avoid it reformatting the whole file when I save. The flake errors should be fixed now.

**Pull request merged**
