### PR TITLE
Configure pre-commit and pre-commit CI

### LINKED ISSUE #1285: Pre-commit hooks
Pre-commit allows for the automated running of linting workflows before a commit is finalised, even applying automatic fixes. This is particularly useful for linting, so that linting errors can be corrected before a commit is even made (hence reduced reliance on the linting action to pickup linting errors).

I propose the following hooks as a baseline (a list of popular hooks are available [here](https://github.com/pre-commit/pre-commit-hooks)):
- check-yaml (verify yaml syntax)
- end-of-file-fixer (adds newline to end of files)
- trailing-whitespace (trims trailing whitespace)
- black (autoformats python files, related to #1284)

### PR DESCRIPTION
**Pull request by VeckoTheGecko**
[Pre-commit](https://pre-commit.com) and [pre-commit CI](https://pre-commit.ci/) allow for the quick and seamless detection (and in some cases auto-fixing) of various code quality issues (aka. pre-commit hooks, full list [here](https://pre-commit.com/hooks.html)).

If precommit is to be used locally:
- install `pre-commit` from PYPI/Conda-forge (`pip install pre-commit`, or `conda install -c conda-forge pre-commit`)
- run `pre-commit install` to set up the hooks listed in `.pre-commit-config.yaml`

Now when you commit, the hooks will be run before the commit is executed (aborting the commit if the hooks pick up errors they can't autofix).

For pre-commit CI, once configured it works automatically on PRs using the same `.pre-commit-config.yaml`. It commits to the branch for automatic fixes, and gives informative logs for changes it can't autofix.

This pre-commit workflow would replace GitHub actions for linting workflows.

Current hooks:
- trailing-whitespace
- end-of-file-fixer
- check-yaml
- check-ast (checks files parse as valid Python)
- flake8

Potential additional hooks:
- tabs to spaces
- docstring linting (future)
- code formatting (#1284)

Configuration of pre-commit CI:
- [x] Go to [pre-commit.ci](https://pre-commit.ci/), sign in with GitHub, and authorize on this repo

Fixes #1285

### CODE REVIEW

**Comment by VeckoTheGecko** [comment]
Converted to draft (waiting on outcome of #1283)

**Comment by VeckoTheGecko** [comment]
Is this something that would be welcome in Parcels? If so, should we add [`pre_commit`](https://anaconda.org/conda-forge/pre_commit) as a dev dependency so people can set up the hooks locally?

**Comment by erikvansebille** [comment]
> Is this something that would be welcome in Parcels? If so, should we add [`pre_commit`](https://anaconda.org/conda-forge/pre_commit) as a dev dependency so people can set up the hooks locally?

I think the option of using the pre-commit workflow is nice! I just tried it and it works smoothly. So yes, let's add `pre-commit` to the environment files. Do you want to do that, @VeckoTheGecko?

**Comment by VeckoTheGecko** [comment]
> Do you want to do that, @VeckoTheGecko?

Happy to do so. Will do it within the hour

**Comment by VeckoTheGecko** [comment]
Should I also remove the flake8 workflow @erikvansebille ? If we're using pre-commit CI, then we'd have doubleup with the flake8 linting (GitHub actions + precommit CI)

**Pull request merged**
