### PR TITLE
CI: micromamba and environment caching

### PR DESCRIPTION
**Pull request by VeckoTheGecko**
Migrating to micromamba with environment caching to reduce CI times.

Environment cache key is based on:
- OS
- runner architecture
- python version
- date
- environment file

### CODE REVIEW

**Comment by VeckoTheGecko** [comment]
Well, looks like it only saves a minute (and its the windows tests that are the main slowdown anyway, and those aren't affected).

---

<details><summary>Details</summary>
<p>

Before:
image

After (cold start):
image

After (warm start):
image</p>
</details>

**Comment by VeckoTheGecko** [comment]
Thoughts on this @erikvansebille ? No significant speedup, but I do have a very slight preference for micromamba for CI . I'm happy either way, just want to clear this out of the open PRs :)

**Comment by erikvansebille** [comment]
> Thoughts on this @erikvansebille ? No significant speedup, but I do have a very slight preference for micromamba for CI . I'm happy either way, just want to clear this out of the open PRs :)

I'd be prefer to keep the installation method of our CI as close to that advised in the [installation instructions for users/developers](https://docs.oceanparcels.org/en/latest/installation.html), so that our CI also tests installation procedure. So rather stick with conda for now...

**Comment by VeckoTheGecko** [comment]
Roger that :)

**Pull request closed without merging**
