### PR TITLE
DOC: API reference restructure, contributing guidelines, and more...

### PR DESCRIPTION
**Pull request by VeckoTheGecko**
Part of #1324

- [x] API reference sectioning (making it easier to navigate)
  - Used the same modules that were covered in the prior documentation
- [x] Add contributing guidelines
- [x] Version switcher
  - Waiting on feedback from https://github.com/pydata/pydata-sphinx-theme/pull/1005#issuecomment-1493381984 about whether the version switcher from RTD can be used by default on desktop machines. Will see how to proceed from there.
    - Won't fix
- [x] Disable search engine indexing of previous versions
- [x] Automatic updating of copyright year (as per https://github.com/OceanParcels/parcels/pull/1341#issuecomment-1493318063)
- [x] Add support for markdown
- [x] Add backlink in navbar to OceanParcels website
- [x] Render grids in docstrings as raw text (rather than HTML table)
- [x] Rendering improvements (fixing numbered lists, inline code formatting)

[RTD deployment](https://veckoparcels.readthedocs.io/en/my_docs-new_layout/). Keen to hear what you think about these changes @erikvansebille

### CODE REVIEW

**Comment by VeckoTheGecko** [comment]
The documentation ([old](https://parcels.readthedocs.io/en/latest/#module-parcels.compilation), and [on this branch](https://veckoparcels.readthedocs.io/en/my_docs-new_layout/reference/code_generation.html)) make reference to the `parcels.compilation` module, but there's no docs for this resulting in a blank section. Should this be removed?

**Comment by VeckoTheGecko** [comment]
> whether the version switcher from RTD can be used by default on desktop machines

Turns out that the RTD version switcher is only visible (a) on mobile (or if you decrease your screen size) and (b) on pages that have subsectioning (eg. the API reference).

Although a bit buggy, I think this is fine and there's no need to take additional action to implement/maintain the other version swticher (most users will be using the most up to date docs anyway).

**Comment by VeckoTheGecko** [comment]
Got some failures in CI.
- `FAILED examples/example_dask_chunk_OCMs.py::test_mitgcm[False-auto-jit]`
- `FAILED examples/example_dask_chunk_OCMs.py::test_mitgcm[True-auto-jit]`

I'm not sure why they're cropping up now particularly in a documentation PR (perhaps a problem with dependencies?). Can investigate this weekend.

<details><summary>Error log</summary>
<p>

```
=================================== FAILURES ===================================
_________________________ test_mitgcm[False-auto-jit] __________________________

mode = 'jit', chunk_mode = 'auto', using_add_field = False

    @pytest.mark.parametrize('mode', ['jit'])
    @pytest.mark.parametrize('chunk_mode', [False, 'auto', 'specific_same', 'specific_different'])
    @pytest.mark.parametrize('using_add_field', [False, True])
    def test_mitgcm(mode, chunk_mode, using_add_field):
        if chunk_mode in ['auto', ]:
            dask.config.set({'array.chunk-size': '256KiB'})
        else:
            dask.config.set({'array.chunk-size': '128MiB'})
        field_set = fieldset_from_mitgcm(chunk_mode, using_add_field)
        lons, lats = 5e5, 5e5
    
        pset = ParticleSet.from_list(fieldset=field_set, pclass=ptype[mode], lon=lons, lat=lats)
        pset.execute(AdvectionRK4, runtime=delta(days=1), dt=delta(minutes=5))
        # MITgcm sample file dimensions: time=10, XG=400, YG=200
        if chunk_mode != 'specific_different':
>           assert (len(field_set.U.grid.load_chunk) == len(field_set.V.grid.load_chunk))
E           assert 6 == 9
E            +  where 6 = len(array([2, 0, 0, 0, 0, 0], dtype=int32))
E            +    where array([2, 0, 0, 0, 0, 0], dtype=int32) = <parcels.grid.RectilinearZGrid object at 0x133022cd0>.load_chunk
E            +      where <parcels.grid.RectilinearZGrid object at 0x133022cd0> = <parcels.field.Field object at 0x13351b810>.grid
E            +        where <parcels.field.Field object at 0x13351b810> = <parcels.fieldset.FieldSet object at 0x132469650>.U
E            +  and   9 = len(array([2, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))
E            +    where array([2, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32) = <parcels.grid.RectilinearZGrid object at 0x12fa376d0>.load_chunk
E            +      where <parcels.grid.RectilinearZGrid object at 0x12fa376d0> = <parcels.field.Field object at 0x1331e1a50>.grid
E            +        where <parcels.field.Field object at 0x1331e1a50> = <parcels.fieldset.FieldSet object at 0x132469650>.V

examples/example_dask_chunk_OCMs.py:406: AssertionError
------------------------------ Captured log call -------------------------------
INFO     parcels.tools.loggers:basekernel.py:262 Compiled ArrayJITParticleAdvectionRK4 ==> /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parcels-501/lib3e60190675569a631d0c7b5f389697e1_0.so
__________________________ test_mitgcm[True-auto-jit] __________________________

mode = 'jit', chunk_mode = 'auto', using_add_field = True

    @pytest.mark.parametrize('mode', ['jit'])
    @pytest.mark.parametrize('chunk_mode', [False, 'auto', 'specific_same', 'specific_different'])
    @pytest.mark.parametrize('using_add_field', [False, True])
    def test_mitgcm(mode, chunk_mode, using_add_field):
        if chunk_mode in ['auto', ]:
            dask.config.set({'array.chunk-size': '256KiB'})
        else:
            dask.config.set({'array.chunk-size': '128MiB'})
        field_set = fieldset_from_mitgcm(chunk_mode, using_add_field)
        lons, lats = 5e5, 5e5
    
        pset = ParticleSet.from_list(fieldset=field_set, pclass=ptype[mode], lon=lons, lat=lats)
        pset.execute(AdvectionRK4, runtime=delta(days=1), dt=delta(minutes=5))
        # MITgcm sample file dimensions: time=10, XG=400, YG=200
        if chunk_mode != 'specific_different':
>           assert (len(field_set.U.grid.load_chunk) == len(field_set.V.grid.load_chunk))
E           assert 6 == 9
E            +  where 6 = len(array([2, 0, 0, 0, 0, 0], dtype=int32))
E            +    where array([2, 0, 0, 0, 0, 0], dtype=int32) = <parcels.grid.RectilinearZGrid object at 0x133145190>.load_chunk
E            +      where <parcels.grid.RectilinearZGrid object at 0x133145190> = <parcels.field.Field object at 0x1332bdfd0>.grid
E            +        where <parcels.field.Field object at 0x1332bdfd0> = <parcels.fieldset.FieldSet object at 0x1324d90d0>.U
E            +  and   9 = len(array([2, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))
E            +    where array([2, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32) = <parcels.grid.RectilinearZGrid object at 0x132a26b90>.load_chunk
E            +      where <parcels.grid.RectilinearZGrid object at 0x132a26b90> = <parcels.field.Field object at 0x132ce2950>.grid
E            +        where <parcels.field.Field object at 0x132ce2950> = <parcels.fieldset.FieldSet object at 0x1324d90d0>.V

examples/example_dask_chunk_OCMs.py:406: AssertionError
------------------------------ Captured log call -------------------------------
INFO     parcels.tools.loggers:basekernel.py:262 Compiled ArrayJITParticleAdvectionRK4 ==> /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parcels-501/lib7155c66477c72b6186bbd769d4d22c54_0.so
=============================== warnings summary ===============================
../../../micromamba-root/envs/py3_parcels/lib/python3.11/site-packages/_pytest/nodes.py:633: 29 warnings
  /Users/runner/micromamba-root/envs/py3_parcels/lib/python3.11/site-packages/_pytest/nodes.py:633: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to IPyNbFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)

examples/example_moving_eddies.py::test_moving_eddies_fwdbwd[flat-scipy]
examples/example_moving_eddies.py::test_moving_eddies_fwdbwd[flat-jit]
examples/example_moving_eddies.py::test_moving_eddies_fwdbwd[spherical-scipy]
examples/example_moving_eddies.py::test_moving_eddies_fwdbwd[spherical-jit]
  /Users/runner/micromamba-root/envs/py3_parcels/lib/python3.11/site-packages/_pytest/python.py:181: PytestUnhandledCoroutineWarning: async def functions are not natively supported and have been skipped.
  You need to install a suitable plugin for your async framework, for example:
    - anyio
    - pytest-asyncio
    - pytest-tornasync
    - pytest-trio
    - pytest-twisted
    warnings.warn(PytestUnhandledCoroutineWarning(msg.format(nodeid)))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated html file: file:///Users/runner/work/parcels/parcels/macos_integration_test_report.html -
=========================== short test summary info ============================
FAILED examples/example_dask_chunk_OCMs.py::test_mitgcm[False-auto-jit] - ass...
FAILED examples/example_dask_chunk_OCMs.py::test_mitgcm[True-auto-jit] - asse...
= 2 failed, 378 passed, 4 skipped, 102 deselected, 4 xfailed, 33 warnings in 2585.06s (0:43:05) =
Error: Process completed with exit code 1.
```

</p>
</details>

**Comment by erikvansebille** [comment]
Thanks @VeckoTheGecko, the new Docs look great! I just pushed a few commits to clean-up some minor issues (and added a favicon 😄), this should be all good now. Are you happy for me to merge into `new_docs`

**Pull request merged**
